import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <nav className="p-4 bg-gray-100 flex gap-4">
          <a href="/login" className="text-blue-600">Login</a>
          <a href="/register" className="text-blue-600">Register</a>
        </nav>
        <div className="p-4">{children}</div>
      </body>
    </html>
  );
}
